### ISSUE TITLE
Add "Add resource" button

### ISSUE THREAD

**Issue by joscha** [AKERKits/akermap#17]
Add an "Add resource" button to the map. This needs to translate an address into latitude/longitude before submitting the form.

**Comment by trizcs** [comment]
Great work Joscha!

It would be ideal if when you fill in the address, the pin automatically goes to that location. Right now, it just goes wherever you click it on the map.

Aaron tells me you were having issues with this, but just thought I'd share!

Cheers mate - it looks fantastic!
