### ISSUE TITLE
Make it look nice

### ISSUE THREAD

**Issue by joscha** [AKERKits/akermap#4]

**Comment by Amakaruk** [comment]
Mockup

![aker-map-mockup](https://cloud.githubusercontent.com/assets/2213029/6586558/054624d4-c740-11e4-85b5-fc1d888205a0.jpg) 
- [x] Make MENU Icon White When Overlaying Map
- [x] Make Menu Background #F7F7FA w/ Black Text
- [x] Add padding to form
- [x] Add padding to resource overlay boxes
- [ ] Button on map - 'Add Resource'
- [x] IGG Campaign Link - 'Get Your AKER Kit!'
- [x] Add Social Media Icons

**Comment by joscha** [comment]
Cool, I'll try to incorporate as much of that as I can by Thursday. If you have more screens feel free to add them to this issue.
Have you checked out the source lately? We should talk about one or two things once the first draft is online and then we can go from there.

**Comment by Amakaruk** [comment]
It's late here - I'll elaborate tomorrow, but we should have an 'About' link that fires a dropdown modal. In the window that appears, we should give you a bunch of credit, host your photo, link to your website(s) etc. I'll make a mockup, but feel free to comment and make suggestions, give feedback, etc.

**Comment by joscha** [comment]
@Amakaruk made all the changes except the add resource button, because that is a bit more tricky because we have to read the location data from the given address - will track this in #17.

**Comment by Amakaruk** [comment]
Ok - it's not deployed yet, right - I just checked - I'm about to add
CNAME's

**Comment by joscha** [comment]
@Amakaruk it's live now :)

**Comment by Amakaruk** [comment]
!!! Great work! - any way to have the IGG part shown all the time - if
that's a hassle don't worry about it.

**Comment by Amakaruk** [comment]
Please change the <title></title> to The AKER Map - not a huge issue :+1:

**Comment by joscha** [comment]
@Amakaruk I added a permanent overlay in e9b2e316ede2633547d4b5a2bb703189bca30f36 - should be live in a few minutes. Regarding the second message you sent, there is some text missing - what should be changed?

**Comment by Amakaruk** [comment]
Some text is missing..not sure what you're referring to. Please clarify

**Comment by joscha** [comment]
![make_it_look_nice_ _issue__4_ _akerkits_akermap](https://cloud.githubusercontent.com/assets/188038/6607679/ed009c18-c840-11e4-91d0-6dfb2ee84d78.png)

**Comment by Amakaruk** [comment]
Ok thanks - I put title tags there - i guess the markdown didn't render
them - just asking you to capitalize the page title in the header - the
info that shows up in the browser tab

**Comment by joscha** [comment]
Got it :+1:  and done - feel free to go ahead and make any changes like this in the repository yourself at any time.

**Comment by Amakaruk** [comment]
Ok awesome - was wondering if I could start doing that - will do Joscha -
thanks
