### ISSUE TITLE
Add AKERKit locations

### ISSUE THREAD

**Issue by joscha** [AKERKits/akermap#7]
Can we use IGG for this?

**Comment by Amakaruk** [comment]
I believe so - tell me more of what you're thinking, and I'll find out for sure.

**Comment by joscha** [comment]
Ideally we would query the backers out of the IGG API that specifically backed to get an AKERKit and use that separately in a layer with this pin: https://github.com/AKERKits/akermap/blob/master/client/images/pins/aker_kit.svg
