### ISSUE TITLE
Sanitize incoming data

### ISSUE THREAD

**Issue by joscha** [AKERKits/akermap#9]
via `$sanitize`.

**Comment by Amakaruk** [comment]
@joscha - if we use something like this:
https://formkeep.com

We can require accounts for people to add data and vet them that way. We can see who submitted each map posting - it might be interesting and straightforward to implement. What do you think?

**Comment by joscha** [comment]
The sanitizing of this ticket is still needed however, independently of the endpoint.

Formkeep: Never used it, but I think so, however with the free plan we’ll only be able to see the most recent 10 submissions though - the minimum plan is 1$ I think, as it is pay what you want.
It pages submissions ins steps of 25 though, so we need multiple requests to get the result...not sure that's ideal.

**Comment by joscha** [comment]
https://developers.google.com/gdata/samples/spreadsheet_sample would probably work as well...

**Comment by Amakaruk** [comment]
Ok great - you're on it
